### ISSUE TITLE
方法缺失问题

### ISSUE THREAD

**Issue by niuzm** [macrozheng/mall-admin-web#10]
商品\商品列表  下
handleShowVerifyDetail（审核详情）
handleShowProduct（查看）
handleShowLog（日志）
这三个js方法丢失，页面功能无法正常使用，您提供的访问网址上这几个功能也无法正常使用，另外自己down下来的项目也是一样缺失这些方法。期待您的回答

**Comment by IEB-Richard** [comment]
应该是还没有开发，我也在找。仓主的框架可以，能否统一一下思路，大家一起开发？

**Comment by macrozheng** [comment]
这些功能还未实现
