### ISSUE TITLE
关于开启history模式

### ISSUE THREAD

**Issue by hdtopku** [macrozheng/mall-admin-web#103]
```
mode: 'history', //后端支持可开
```
如上，打开`history`后，出现如下报错
```
 Uncaught SyntaxError: Unexpected token '<'
```
只需将`config/index.js`中的，`assetsPublicPath:'./'`改为`assetsPublicPath:'/'`即可

参考：
[https://github.com/umijs/qiankun/issues/223](https://github.com/umijs/qiankun/issues/223)、
[https://www.h5w3.com/12807.html](https://www.h5w3.com/12807.html)

**Comment by macrozheng** [comment]
如果这样修改话，项目打包后会无法在子目录下部署。
