### ISSUE TITLE
执行npm install命令报错

### ISSUE THREAD

**Issue by maxiaofang-nnn** [macrozheng/mall-admin-web#105]
![QQ截图20201102164041](https://user-images.githubusercontent.com/27114816/97849436-89595900-1d2d-11eb-91e2-9393d6952860.png)

**Comment by maxiaofang-nnn** [comment]
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (E:\mall\mall-admin-web\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (E:\mall\mall-admin-web\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at E:\mall\mall-admin-web\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:183:21)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "E:\\developTool\\nodejs\\node.exe" "E:\\mall\\mall-admin-web\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\mall\mall-admin-web\node_modules\node-sass
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN echarts-liquidfill@2.0.3 requires a peer of echarts@^4.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN v-charts@1.19.0 requires a peer of echarts@>3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.13.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ktu56\AppData\Roaming\npm-cache\_logs\2020-11-02T08_29_32_924Z-debug.log

**Comment by luoxing200809** [comment]
用国内镜像 cnpm install  可以

**Comment by KaygNas** [comment]
安装 node-sass 包的问题, 自己手动再安装最新版也能解决

**Comment by TinsFox** [comment]
```
# 安装依赖
npm install

# 建议不要用 cnpm 安装 会有各种诡异的bug 可以通过如下操作解决 npm 下载速度慢的问题
npm install --registry=https://registry.npm.taobao.org

# 本地开发 启动项目
npm run dev
```
