### ISSUE TITLE
管理后台用户角色权限

### ISSUE THREAD

**Issue by chandlerFan** [macrozheng/mall-admin-web#11]
用户、权限、角色的管理还缺失了，我可以一起开发，想问下现在有在计划开发吗？还是正 在开发？

**Comment by macrozheng** [comment]
角色权限相关接口在mall-admin的接口文档中都能找到:http://39.98.190.128:8080/swagger-ui.html#/UmsPermissionController ，页面还未开发。

**Comment by IceIris-c** [comment]
请问能不能解释一下权限创建

**Comment by macrozheng** [comment]
权限功能已经添加
