### ISSUE TITLE
项目打包 报错 npm run build 求解决,谢谢!

### ISSUE THREAD

**Issue by gaozijun121** [macrozheng/mall-admin-web#115]
报错如下..
 static/tinymce4.7.5/tinymce.min.js     834 kB          [emitted]  [big]

ERROR in static/js/app.c412c86855436680c229.js from UglifyJs
Unexpected token punc «:», expected punc «,» [./src/utils/request.js:8,11][static/js/app.c412c86855436680c229.js:2670,15
]

也百度过了....用了好多方法都没用

**Comment by irezm** [comment]
可以使用yarn，我是用npm install就报错了，使用yarn没问题
yarn install
yarn dev
