### ISSUE TITLE
可以升级一下node-sass的版本吗

### ISSUE THREAD

**Issue by zshnb** [macrozheng/mall-admin-web#121]
项目自带版本执行npm install报错，https://github.com/sass/node-sass/releases/download/v4.13.0/win32-x64-83_binding.node 这个地址已经不存在了，我手动升级到5.0.0就可以npm install了。

**Comment by liutingfenga** [comment]
你好，我现在手动安装后还是报错 无法运行项目，请问具体解决方法，谢谢
