### ISSUE TITLE
构建失败

### ISSUE THREAD

**Issue by heihei180** [macrozheng/mall-admin-web#124]
Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

尝试新的跨平台 PowerShell https://aka.ms/pscore6

PS D:\code\html\mall-admin-web> npm install

> node-sass@4.13.0 install D:\code\html\mall-admin-web\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.0/win32-x64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.0/win32-x64-83_binding.node": 

connect ETIMEDOUT 52.74.223.119:443

Timed out whilst downloading the prebuilt binary

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> uglifyjs-webpack-plugin@0.4.6 postinstall D:\code\html\mall-admin-web\node_modules\webpack\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js

> node-sass@4.13.0 postinstall D:\code\html\mall-admin-web\node_modules\node-sass
> node scripts/build.js

Building: D:\tools\nodejs\node.exe D:\code\html\mall-admin-web\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'D:\\tools\\nodejs\\node.exe',
gyp verb cli   'D:\\code\\html\\mall-admin-web\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.15.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Program Files\python" in the PATH
gyp verb `which` failed Error: not found: C:\Program Files\python
gyp verb `which` failed     at getNotFoundError (D:\code\html\mall-admin-web\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\code\html\mall-admin-web\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\code\html\mall-admin-web\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\code\html\mall-admin-web\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\code\html\mall-admin-web\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\code\html\mall-admin-web\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21)
gyp verb `which` failed  C:\Program Files\python Error: not found: C:\Program Files\python
gyp verb `which` failed     at getNotFoundError (D:\code\html\mall-admin-web\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\code\html\mall-admin-web\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\code\html\mall-admin-web\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\code\html\mall-admin-web\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\code\html\mall-admin-web\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\code\html\mall-admin-web\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb could not find "C:\Program Files\python". checking python launcher
gyp verb could not find "C:\Program Files\python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "C:\Program Files\python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\code\html\mall-admin-web\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\code\html\mall-admin-web\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at D:\code\html\mall-admin-web\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:183:21)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "D:\\tools\\nodejs\\node.exe" "D:\\code\\html\\mall-admin-web\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\code\html\mall-admin-web\node_modules\node-sass
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.13.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2021-05-29T00_06_01_594Z-debug.log
PS D:\code\html\mall-admin-web> npm install

> node-sass@4.13.0 install D:\code\html\mall-admin-web\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.0/win32-x64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.0/win32-x64-83_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.13.0 postinstall D:\code\html\mall-admin-web\node_modules\node-sass
> node scripts/build.js

Building: D:\tools\nodejs\node.exe D:\code\html\mall-admin-web\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'D:\\tools\\nodejs\\node.exe',
gyp verb cli   'D:\\code\\html\\mall-admin-web\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.15.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Program Files\python" in the PATH
gyp verb `which` failed Error: not found: C:\Program Files\python
gyp verb `which` failed     at getNotFoundError (D:\code\html\mall-admin-web\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\code\html\mall-admin-web\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\code\html\mall-admin-web\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\code\html\mall-admin-web\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\code\html\mall-admin-web\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\code\html\mall-admin-web\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21)
gyp verb `which` failed  C:\Program Files\python Error: not found: C:\Program Files\python
gyp verb `which` failed     at getNotFoundError (D:\code\html\mall-admin-web\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\code\html\mall-admin-web\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\code\html\mall-admin-web\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\code\html\mall-admin-web\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\code\html\mall-admin-web\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\code\html\mall-admin-web\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb could not find "C:\Program Files\python". checking python launcher
gyp verb could not find "C:\Program Files\python". guessing location 
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "C:\Program Files\python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\code\html\mall-admin-web\node_modules\node-gyp\lib\configure.js:484:19)
PS D:\code\html\mall-admin-web> npm install

> node-sass@4.13.0 install D:\code\html\mall-admin-web\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.0/win32-x64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.0/win32-x64-83_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.13.0 postinstall D:\code\html\mall-admin-web\node_modules\node-sass
> node scripts/build.js

Building: D:\tools\nodejs\node.exe D:\code\html\mall-admin-web\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'D:\\tools\\nodejs\\node.exe',
gyp verb cli   'D:\\code\\html\\mall-admin-web\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.15.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Program Files\python" in the PATH
gyp verb `which` failed Error: not found: C:\Program Files\python
gyp verb `which` failed     at getNotFoundError (D:\code\html\mall-admin-web\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\code\html\mall-admin-web\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\code\html\mall-admin-web\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\code\html\mall-admin-web\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\code\html\mall-admin-web\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\code\html\mall-admin-web\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21)
gyp verb `which` failed  C:\Program Files\python Error: not found: C:\Program Files\python
gyp verb `which` failed     at getNotFoundError (D:\code\html\mall-admin-web\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\code\html\mall-admin-web\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\code\html\mall-admin-web\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\code\html\mall-admin-web\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\code\html\mall-admin-web\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\code\html\mall-admin-web\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb could not find "C:\Program Files\python". checking python launcher
gyp verb could not find "C:\Program Files\python". guessing location 
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "C:\Program Files\python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\code\html\mall-admin-web\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\code\html\mall-admin-web\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at D:\code\html\mall-admin-web\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:183:21)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "D:\\tools\\nodejs\\node.exe" "D:\\code\\html\\mall-admin-web\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\code\html\mall-admin-web\node_modules\node-sass
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN echarts-liquidfill@2.0.3 requires a peer of echarts@^4.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN v-charts@1.19.0 requires a peer of echarts@>3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.13.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2021-05-29T00_08_50_952Z-debug.log

**Comment by heihei180** [comment]
这玩意构建还需要python 环境吗？

**Comment by zjs9609** [comment]
删除package-lock.json文件就能npm install构建成功

**Comment by takeAction** [comment]
以管理员身份打开windows的cmd，执行 `npm install --global --production windows-build-tools@4.0.0` 能解决此问题，但又会遇到另一个问题。
根据 @zjs9609 描述的删除 package-lock.json文件 即能构建成功。

**Comment by AlivinFer** [comment]
遇到同样的问题，请问楼主解决了吗

**Comment by Da-wukong** [comment]
先删除 npm uninstall node-sass
再安装最新版本 npm install node-sass@latest

**Comment by Da-wukong** [comment]
先删除 npm uninstall node-sass
再安装最新版本 npm install node-sass@latest

**Comment by DzwsGo** [comment]
> 

bingo，可行
