### ISSUE TITLE
登陆问失败

### ISSUE THREAD

**Issue by qiyugfh** [macrozheng/mall-admin-web#13]
感谢你的开源，我想问问，为什么我在电脑上调试的时候，网址http://localhost:8090/#/login，输入账号密码admin/123456，为什么登陆不了，一直提示"Network Error"

**Comment by macrozheng** [comment]
自己搭建后台或者使用线上后台API，具体参考readme中的搭建步骤

**Comment by Mrfanwei** [comment]
这个问题你怎么解的，能否说下步骤，我在docker中遇到这个问题
