### ISSUE TITLE
mall-swarm +web 登陆提示

### ISSUE THREAD

**Issue by keweiLv** [macrozheng/mall-admin-web#132]
本地部署后，已更新到git最新sql，首页登陆仍然报错/info 提示无权限导致跳转失败

**Comment by Huo123Chen** [comment]
vue 部署不成功 能教教我吗

**Comment by keweiLv** [comment]
vue直接install应该就可以了哦，报错可能是依赖的版本问题，可以看报错依次解决，记得清理缓存

Huo123Chen ***@***.***> 于2022年1月26日周三 19:42写道：

**Comment by awxiaoxian2020** [comment]
> 本地部署后，已更新到git最新sql，首页登陆仍然报错/info 提示无权限导致跳转失败

给下截图

**Comment by LoEnzo** [comment]
同样 mall-swarm +web，登陆报错如下，我看close的issue有过这个问题，但是没说怎么成功的就close掉了，有知道的吗，感谢
![image](https://user-images.githubusercontent.com/43113063/176143292-88cc5a0e-cfd1-4729-ab7c-39f4c55e7884.png)
