### ISSUE TITLE
node-sass和sass-loader版本不对 导致npm install 报错

### ISSUE THREAD

**Issue by zhangsiqiang001** [macrozheng/mall-admin-web#133]
修改：

**Comment by zhangsiqiang001** [comment]
"node-sass": "^7.0.1",
    "sass-loader": "^7.0.0"

**Comment by zhangsiqiang001** [comment]
报错详情：
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\code\zmcode\study-vue\mall-admin-web\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\code\zmcode\study-vue\mall-admin-web\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\code\zmcode\study-vue\mall-admin-web\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\code\zmcode\study-vue\mall-admin-web\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\code\zmcode\study-vue\mall-admin-web\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\code\zmcode\study-vue\mall-admin-web\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\code\zmcode\study-vue\mall-admin-web\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\code\zmcode\study-vue\mall-admin-web\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\code\zmcode\study-vue\mall-admin-web\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\code\zmcode\study-vue\mall-admin-web\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\code\zmcode\study-vue\mall-admin-web\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\code\zmcode\study-vue\mall-admin-web\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Users\Administrator\AppData\Local\Programs\Python\Python38\python.EXE
npm ERR! gyp ERR! configure error

**Comment by lincome** [comment]
感谢

**Comment by swkee** [comment]
我改了一些依赖，把node-sass换成sass了。用的环境是os:win11, nodejs版本：18.20.4，装了vs2019
"dependencies": {
    "axios": "^0.18.0",
    "echarts": "^4.2.0-rc.2",
    "element-ui": "^2.3.7",
    "js-cookie": "^2.2.0",
    "normalize.css": "^8.0.1",
    "nprogress": "^0.2.0",
    "v-charts": "^1.19.0",
    "v-distpicker": "^1.0.20",
    "vue": "^2.5.2",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.26.3",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-loader": "^7.1.1",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-plugin-transform-vue-jsx": "^3.5.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "chalk": "^2.0.1",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.10",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^1.1.4",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "html-webpack-plugin": "^3.2.0",
    "node-notifier": "^5.1.2",
    "sass": "^1.56.1", 
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^1.2.0",
    "portfinder": "^1.0.32",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.8",
    "postcss-url": "^7.2.1",
    "rimraf": "^2.6.0",
    "sass-loader": "^7.0.1",
    "semver": "^5.3.0",
    "shelljs": "^0.8.5",
    "svg-sprite-loader": "^3.7.3",
    "uglifyjs-webpack-plugin": "^1.1.1",
    "url-loader": "^0.5.8",
    "vue-loader": "^14.2.4",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.5.2",
    "webpack": "^3.12.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-server": "^2.11.5",
    "webpack-merge": "^4.1.0"
  },
