### ISSUE TITLE
关于node-sass安装失败的问题如何解决

### ISSUE THREAD

**Issue by wangdi7670** [macrozheng/mall-admin-web#134]
安装失败的原因一部分是大家本地装的node版本高于node-sass版本，所以安装需要安装高版本的node-sass，但从源地址下载还有可能失败，所以最好从镜像下载。

综上：
```
npm install node-sass@latest --sass-binary-site=https://npm.taobao.org/mirrors/node-sass

```
本地环境：node v16.13.0
[这里有node 和node-sass版本对应关系](https://stackoverflow.com/questions/60394291/error-node-modules-node-sass-command-failed)

**Comment by iamk123** [comment]
有用，先用了楼主这个命令，再npm install就好了

**Comment by DarthVagen** [comment]
install没问题，run dev大概率还是报错，sass-loader版本也得相应升级

**Comment by mark8s** [comment]
nb
