### ISSUE TITLE
侧边菜单栏的名称无法修改

### ISSUE THREAD

**Issue by SukiiL** [macrozheng/mall-admin-web#137]
把前端代码改成这样以后（把title“订单”改成了“综合管理”，“退货申请处理”改成了“坪效相关”）页面上依然显示之前的title。

但是我把修改后的项目打包发给另一台电脑，可以成功显示修改后的页面。

![image](https://user-images.githubusercontent.com/78685619/165273975-1fef6816-b284-4f7c-b4fd-5f02cf251ddf.png)

![66560b7ce833c0eca96928fd8d05b05](https://user-images.githubusercontent.com/78685619/165274241-95a2a75b-639b-4632-99d7-16187c6472e2.png)

**Comment by macrozheng** [comment]
这个名称是后台管理系统控制的，需要在系统的菜单管理功能中修改才可以生效。
