### ISSUE TITLE
登出功能这个接口是不是没起什么作用

### ISSUE THREAD

**Issue by junjialiang** [macrozheng/mall-admin-web#139]
在执行 登出功能接口（/admin/logout）后，然后调用 获取当前登录用户信息（/admin/info）后依然可以正常获取用户信息，是不是登出逻辑只在前端做了处理？（ps. 其它接口也一样可以正常获取到数据）

**Comment by 1641341031** [comment]
/admin/logout这个接口后端的spring security进行处理，/admin/info接口后端获取用户信息会存到cookie；退出的逻辑把把前端的cookie清理的
