### ISSUE TITLE
图片上传oss问题

### ISSUE THREAD

**Issue by Tristanchen** [macrozheng/mall-admin-web#14]
提示跨域，项目在本地跑有障碍吗？同时还有一个问题，源码中upload 组件上传的参数和OSS要求的验证方式是如何匹配的

**Comment by macrozheng** [comment]
搭建了后台，配置了OSS是没有问题的，验证方式匹配具体参考OSS文档：
- 配置跨域：https://help.aliyun.com/document_detail/31928.html
- 验证方式：https://help.aliyun.com/document_detail/31926.html
