### ISSUE TITLE
windows 的部署 mall 方式有谁跑通了吗？

### ISSUE THREAD

**Issue by sthwhl** [macrozheng/mall-admin-web#141]
我正在完善这部分，目前已经 能够登录 admin-mall-web 去访问。
但官方手册中，访问接口文档报 401 ，可以协助我一下吗?
![image](https://user-images.githubusercontent.com/54652351/176359530-6d155609-e94a-4299-8801-9e39493c3296.png)
![image](https://user-images.githubusercontent.com/54652351/176359596-87851fd1-d9de-4351-b8a3-11c663325335.png)

**Comment by sthwhl** [comment]
es,mongodb,mq 是不是都没用起来

**Comment by LucySnappay** [comment]
swager 中如何用token并验证API： 
直接运行localhost:8080/swagger-ui/html

1 先运行这个api接口： /admin/login  
 (注意：body中填好username/password)  然后 execute：
从response中获得 header和token: 
{   "code": 200,   "message": "操作成功",   "data": {     "tokenHead": "Bearer ",     "token": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImNyZWF0ZWQiOjE2NjYzNzA3Nzk3MzEsImV4cCI6MTY2Njk3NTU3OX0.I7MyZ_mLpuHL6CphtWiBXmE6KHsYKnDt4hRXYCwDc6h4hJkW8_tgjPBmEU5SM3A1LTsYrDZ29xmPFOQr8SZ99Q"   } }

2, swagger页面的最前面右上角 有这个按钮 Authorize, 点击一下，根据上面的header和token输入：
Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImNyZWF0ZWQiOjE2NjYzNzA3Nzk3MzEsImV4cCI6MTY2Njk3NTU3OX0.I7MyZ_mLpuHL6CphtWiBXmE6KHsYKnDt4hRXYCwDc6h4hJkW8_tgjPBmEU5SM3A1LTsYrDZ29xmPFOQr8SZ99Q

3，接下来就可以再调试其他的API了
