### ISSUE TITLE
前端项目部署失败

### ISSUE THREAD

**Issue by sultimate** [macrozheng/mall-admin-web#144]
看了其他issues（就那么几个），基本都是前端各种依赖版本过低，脚手架过时，导致无法安装依赖，或者成功启动项目。个人短见：按作者的能力，使用最新的脚手架，重写一个 vue 3 的前端项目，岂不是举手之劳。感觉整个mall最近更新也越来越水了

**Comment by bblzjp** [comment]
前端是不是没人维护？已经很久没有更新了，好多页面都没有

**Comment by qq715436512** [comment]
所以赖版本过低有解决方法了吗，webpack-dev-server版本都试了一个遍还是不行
npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! travel@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`

npm ERR! Exit status 1

npm ERR!

npm ERR! Failed at the travel@1.0.0 dev script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:

npm ERR!    D:\Program Files\nodejs\node_cache\_logs\2018-08-01T09_05_17_312Z-debug.log
-----------------------------------
解决vue项目运行过程中，npm run dev 报错问题

**Comment by qq715436512** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
