### ISSUE TITLE
彻底解决"npm install"时各种报错的一种方案

### ISSUE THREAD

**Issue by HackyleShawe** [macrozheng/mall-admin-web#146]
**主要步骤：** 
1. 使用vue脚手架新建Vue2项目，将src、static目录下的源代码复制到新建项目的指定位置
2. 安装相关依赖
3. 新建vue.config.js，进行如下配置：(1) 关闭eslint；(2) 添加proxy，访问后端（解决跨域问题）

**我的环境：**
- Node：16.14.2
- NPM：8.5.0
- Vue：vue/cli 5.0.4
---
**安装依赖**

安装生产依赖
npm install --save echarts@4.2.0-rc.2
npm install --save js-cookie@2.2.0
npm install --save normalize.css@8.0.0
npm install --save nprogress@0.2.0
npm install --save v-charts@1.19.0
npm install --save v-distpicker@1.0.20
npm install --save vue-router@3.4.9
npm install --save axios@0.26.0
npm install --save vuex@3.6.2
npm install --save element-ui

注意，需要根据NoseJS的版本安装
cnpm install --save-dev node-sass@6.0.1
cnpm install --save-dev sass-loader@10.2.0

---
```javascript
// vue.config.js
module.exports = {
  lintOnSave: false,//是否在保存时检查
  devServer: {
    host: 'localhost',//本机ip
    port: 9020,//本项目使用的端口
    open: true,
    proxy: {
      '/': {  //代理别名
          target: 'http://localhost:8080',   //代理目标值
          changeOrigin: true,
          secure: true,
              pathRewrite:{  //替换路径中的/api
              '^/':'/'
          }
          // pathRequiresRewrite: {
          //   '^/api': ''
          // }
      }
    },
    overlay: {
        warning: false,
        errors: true
    }
  },
  runtimeCompiler: true
}
```

**Comment by HackyleShawe** [comment]
**注意：** 我在一切都搭建完成，执行“npm run serve”后，进入登录页面，报了个错：
![image](https://user-images.githubusercontent.com/30207521/198598739-b025df2b-80f6-40ab-bdb7-1b855bca2dd9.png)

**我的解决方案**
![image](https://user-images.githubusercontent.com/30207521/198599574-90e04f83-56c4-46e9-99f2-15f64f150ec9.png)

**Comment by Tycho457** [comment]
菜单图标不生效了

**Comment by ttddss** [comment]
前端部署的说明：https://www.macrozheng.com/mall/deploy/mall_deploy_web.html

**Comment by cherish710** [comment]
The website is not
