### ISSUE TITLE
关于npm install 报错一些坑

### ISSUE THREAD

**Issue by AleoXZ** [macrozheng/mall-admin-web#153]
1、python版本的问题，这个项目依赖python2环境。
2、node-sass的问题

第2问题我的解决方案参考 https://stackoverflow.com/a/74791591

**Comment by ttddss** [comment]
前端部署的说明：https://www.macrozheng.com/mall/deploy/mall_deploy_web.html

**Comment by marchocode** [comment]
Just install `v12.14.0`

https://nodejs.org/dist/v12.14.0/node-v12.14.0-x64.msi
