### ISSUE TITLE
请问这个不是微服务版本的前端吧，微服务版本的前端在哪里呢

### ISSUE THREAD

**Issue by hahaoshui** [macrozheng/mall-admin-web#155]

**Comment by Bingo1985** [comment]
it is not the micro version. where is the micro?

**Comment by Bingo1985** [comment]
dev.env.js 中修改BASE_API

module.exports = merge(prodEnv, {
  NODE_ENV: '"development"',
  BASE_API: '"http://192.168.1.108:8201/mall-admin"'
})

**Comment by Bingo1985** [comment]
dev.env.js 中修改BASE_API

module.exports = merge(prodEnv, {
NODE_ENV: '"development"',
BASE_API: '"http://host:port[gateway]/mall-admin"'
})
