### ISSUE TITLE
打包好样式不正确,开发模式正常

### ISSUE THREAD

**Issue by wangdexiao** [macrozheng/mall-admin-web#158]
![image](https://github.com/macrozheng/mall-admin-web/assets/13145751/335d848e-6c41-4b5a-9bf0-0ced69ce8452)
这种是什么情况

**Comment by zhang928160849** [comment]
我也是在使用ngnix挂载静态网站时遇到这个问题，看起来css文件是被正确的返回了，以这个login-title为例子：
<img width="803" alt="image" src="https://github.com/user-attachments/assets/96ff20a3-647b-47c3-9d33-7c89fca3b173">
<img width="1151" alt="image" src="https://github.com/user-attachments/assets/6c722ae5-81cd-4c50-a095-fec35fd28ac8">，有思路吗？
