### ISSUE TITLE
分享 npm install 之后启动不了问题

### ISSUE THREAD

**Issue by niemingwang** [macrozheng/mall-admin-web#161]
### 本机环境
![image](https://github.com/macrozheng/mall-admin-web/assets/81463583/1046bd81-ba6b-4475-987e-284318200d4c)

**1. 项目克隆下来之后直接npm install (如果卡住直接ctrl+c结束，这里要确保能装的包已装好，这时启动项目是跑不起来的)**
![image](https://github.com/macrozheng/mall-admin-web/assets/81463583/f3a2794f-6f7d-4138-b77e-951f73485d15)

**2. 然后找到package.json中的node-sass包，删除掉，然后执行cnpm install node-sass -D重新安装（cnpm自行安装https://blog.csdn.net/qq_59012240/article/details/128448457）**

![image](https://github.com/macrozheng/mall-admin-web/assets/81463583/65ef204c-fdc3-4c16-9c46-c41bf99fc88b)

**3.npm run start完事儿**
![image](https://github.com/macrozheng/mall-admin-web/assets/81463583/32562e10-efdb-4258-bfc4-af80e3733b6f)

**Comment by ghost** [comment]
https://juejin.cn/post/7291657927995670563
https://blog.csdn.net/username666/article/details/105385738
