### ISSUE TITLE
运行登录失败, API修改为线上

### ISSUE THREAD

**Issue by singgl** [macrozheng/mall-admin-web#17]
本地运行 API改为线上还是失败 还是本地运行一定要搭建后台才行

**Comment by IEB-Richard** [comment]
这个Project一定需要在本地跑后端才可以的，你打开另外一个项目，按照说明部署一下再试试呢。

**Comment by macrozheng** [comment]
config/dev.env.js文件中的这段改下：`module.exports = merge(prodEnv, {
  NODE_ENV: '"development"',
  BASE_API: '"http://39.98.190.128:8080"'
})`
