### ISSUE TITLE
前端项目npm install报错

### ISSUE THREAD

**Issue by muchenxiaoxi** [macrozheng/mall-admin-web#19]
前端项目npm install 报错

![日志信息](https://user-images.githubusercontent.com/19276576/54176993-bd826500-44cb-11e9-83e3-3b3dde267ce1.png)

![报错的插件](https://user-images.githubusercontent.com/19276576/54176844-4ea50c00-44cb-11e9-8899-99581a881b70.png)
![报错信息](https://user-images.githubusercontent.com/19276576/54176849-5369c000-44cb-11e9-969a-3171718c13c9.png)

)

**Comment by WillianLiusHao** [comment]
清一下node缓存，或者升级一下npm版本试试，我也和你一样，清缓存后再install就ok了

**Comment by muchenxiaoxi** [comment]
升级了npm版本可以了，谢谢。
