### ISSUE TITLE
借鉴和合作

### ISSUE THREAD

**Issue by linlinjava** [macrozheng/mall-admin-web#2]
你好，我现在也做了类似springboot+vue-element的商场系统，https://github.com/linlinjava/litemall。
虽然关注比你多点，但是其实是我基于别的开源项目整合以及写的文档骗来的。由于自身前端能力较差，能不能参考或者拷贝前端少量代码。当然我会在readme里面写上你这里参考出处。当然，如果你觉得不合适，那我就自己摸索写吧。实际上，你后端技术也很强，不知道能不能合作和学习。

**Comment by macrozheng** [comment]
可以，互相学习

**Comment by linlinjava** [comment]
好的，多谢。
我在我建的开发群里也推荐了你的项目，觉得你的数据库设计更为完善和复杂，开发技术上涉及的也较多。
或许你也可以建个QQ群什么的。

**Comment by macrozheng** [comment]
好的，多谢你建议

**Comment by IEB-Richard** [comment]
感谢两位，你们的项目我都有参考，希望能有机会多交流
