### ISSUE TITLE
对接后端接口，无法执行then的跳转

### ISSUE THREAD

**Issue by LinYue430** [macrozheng/mall-admin-web#21]
后端接口返回200，参数正常，但是不执行then方法，走的是catch，提示红框。

**Comment by macrozheng** [comment]
具体是哪个接口呢，是登录么

**Comment by LinYue430** [comment]
首先感谢你的回复！
是的，的确是登陆。目前有个问题，接口已经返回200，参数正常，但是页面无法跳转，也就是无法执行then的内容

发件人: macro
发送时间: 2019年4月8日 22:00
收件人: macrozheng/mall-admin-web
抄送: ZhaoLY; Author
主题: Re: [macrozheng/mall-admin-web] 对接后端接口，无法执行then的跳转 (#21)

具体是哪个接口呢，是登录么

**Comment by macrozheng** [comment]
我试了下修改为线上api是可以的，可以参考下这个https://github.com/macrozheng/mall-admin-web/issues/17
