### ISSUE TITLE
部署后上文路径容易出错

### ISSUE THREAD

**Issue by w17731138318** [macrozheng/mall-admin-web#22]
config 文件中 index.js 其中  assetsPublicPath: './', 应该改为相对路径不然
 当 nginx 中
 location /mall {
        alias   /usr/share/nginx/mall;
        index  index.html index.htm;
    }
这样配置时会出现访问静态资源路径不正确的问题

**Comment by DevenWen** [comment]
hi，我也在郁闷部署的问题。请问还有其他办法解决么？除了改动代码外 @w17731138318

**Comment by w17731138318** [comment]
就是需要改代码。。

**Comment by DevenWen** [comment]
我按照你的思路，修改了代码已经正常部署了

伟鑫 <notifications@github.com>于2019年5月15日 周三上午10:57写道：
