### ISSUE TITLE
使用Docker有问题

### ISSUE THREAD

**Issue by JifeiMei** [macrozheng/mall-admin-web#26]
我在windows下`npm run dev`没问题，打包、解决静态资源访问的问题，搞完之后打镜像、run，访问的时候只能看到登陆界面，登不进去（确保后端调用没障碍，全部在云服务器）；  
好吧我怀疑是打包有问题，咱再尝试一个思路，在linux上run dev试试  
使用node+python镜像，把源码拷进去，npm install、npm run dev  
跑起来了，访问一下还是一样的问题  
（浏览器完全没报错，就是没法登陆）

**Comment by Mrfanwei** [comment]
能不能提供下你的dockerfile和docker compose文件,或者对应的pull的docker image名字，我也想做成docker，直接用node镜像一直有问题

**Comment by JifeiMei** [comment]
> 能不能提供下你的dockerfile和docker compose文件,或者对应的pull的docker image名字，我也想做成docker，直接用node镜像一直有问题

编译好的用nginx，如果是源码在开发环境下运行，用nikolaik/python-nodejs:python3.5-nodejs10

**Comment by Mrfanwei** [comment]
我直接放到nginx中，在docker compose中配置links，在代码中通过links的别名访问会出现network error问题，如果在代码中改成通过docker ip访问就是正常的，这个问题有遇到过吗

**Comment by JifeiMei** [comment]
> 我直接放到nginx中，在docker compose中配置links，在代码中通过links的别名访问会出现network error问题，如果在代码中改成通过docker ip访问就是正常的，这个问题有遇到过吗

好像碰到过类似的问题，但是一个‘network error’不能让我回忆出来怎么解决的，有详细的错误信息吗？

**Comment by Mrfanwei** [comment]
![微信图片_20190531140810](https://user-images.githubusercontent.com/18242646/58685231-8aa28b80-83ad-11e9-9dd8-4600236577d0.png)

**Comment by JifeiMei** [comment]
你这是后端的接口不通，前端是运行在你本地的浏览器上的，如果你调用后端接口BASE_PATH=mall-admin:8080，你的浏览器就会解析mall-admin的DNS，实际上在你本机上是找不到这个host的，浏览器里按F12选择网络，刷新，你会看到请求的资源。  
VUE的页面跟JSP不一样，并不是在docker里面请求后端数据让浏览器渲染的，而是传给浏览器静态的文件，浏览器根据传过来的文件再去解析需要请求什么资源，到哪里请求。  
如果你非要用别名这种形式，可以把后端的端口代出来（ports: - 8080:8080）,然后把你运行后端服务的虚拟机的IP添加到host或者你的路由器DNS，别名为你的后端服务docker的name。

以上是我对你描述的问题的理解和建议，不知道是不是你说的这种问题，理解错了的话别见怪。

**Comment by Mrfanwei** [comment]
确实是这样的，谢谢了
