### ISSUE TITLE
前端登录不了

### ISSUE THREAD

**Issue by Mrfanwei** [macrozheng/mall-admin-web#28]
我在一台电脑上运行mall-admin-web，在本地是能正常登录的，但是在另外一台电脑上通过浏览器不能登录(能进入登录界面)，请问这是什么问题，下图是调试相关信息

![微信图片_20190531164436](https://user-images.githubusercontent.com/18242646/58693512-884b2c00-83c3-11e9-9cf3-8a6faf29ed4a.png)

**Comment by Mrfanwei** [comment]
在config->index.js->build中加入下面的就可以了，ip和port要改成自己的
 host: '192.168.1.156', // can be overwritten by process.env.HOST
    port: 8090, // can be overwritten by process.env.PORT, if port is in use, a free one will be determined

**Comment by qigecanghai** [comment]
把登录页面中一段代码注掉
            // let isSupport = getSupport();
            // if(isSupport===undefined||isSupport==null){
            //   console.log(4)
            //   this.dialogVisible =true;
            //   return;
            // }
