### ISSUE TITLE
sidebarItem多层路由嵌套的时候，路由路经显示不正确

### ISSUE THREAD

**Issue by keyiwu** [macrozheng/mall-admin-web#3]
比如这样
// 营销中心 分为优惠券管理和礼品卡管理
import Layout from '@/views/layout/Layout'

const ticketRouter = {
  path: '/ticket',
  component: Layout,
  redirect: '/ticket/couponBatch/index',
  name: 'Ticket',
  meta: {
    title: '营销中心',
    icon: 'sms'
  },
  children: [{
    path: 'couponBatch',
    name: 'CouponBatch',
    redirect: '/CouponBatch/index',
    component: () => import('@/views/ticket/couponBatch/index'), // Parent router-view
    meta: {
      title: '优惠券管理',
      icon: 'sms'
    },
    children: [{
      path: 'CouponBatch/index',
      name: 'CouponBatchIndex',
      component: () => import('@/views/ticket/couponBatch/index'),
      meta: {
        title: '优惠券管理',
        icon: 'sms'
      }
    }]
  },
    {
      path: 'gifts',
      component: () => import('@/views/ticket/gifts/index'), // Parent router-view
      name: 'Gifts',
      redirect: '/ticket/gifts/index',
      children: [{
        path: 'index',
        component: () => import('@/views/ticket/gifts/index'),
        name: 'GiftIndex',
        meta: {
          title: '礼品卡管理',
          icon: 'sms'
        }
      }
      ]
    }
  ]
}
export default ticketRouter

**Comment by keyiwu** [comment]
解决方案，三级路由嵌套时候，需要一个router-view作为容器

**Comment by virtuecai** [comment]
> 解决方案，三级路由嵌套时候，需要一个router-view作为容器

请问能否贴上一部分实现代码
