### ISSUE TITLE
oss web 直传不回调未使用回调

### ISSUE THREAD

**Issue by virtuecai** [macrozheng/mall-admin-web#34]
https://github.com/macrozheng/mall-admin-web/blob/e19b9a6328a5fa10cd33b81bfbeef4a3109cd4d7/src/components/Upload/singleUpload.vue#L88  

未使用回调的原因，是不是因为文件的访问路径是可以预知根据图片路径+名称等提前得到文件地址，从而省略了一步；如果说需要对所有上传的文件进行逻辑管理的话， 就需要回调处理。

**Comment by macrozheng** [comment]
不使用回调的原因是：回调地址必须是公网可以访问的地址，很多人都没有。
