### ISSUE TITLE
功能还会完善吗？

### ISSUE THREAD

**Issue by tianshaokai** [macrozheng/mall-admin-web#36]
1.点击审核详情 没有反应
2.动态权限问题，不同用户访问不同页面
目前普通用户访问总是提示这个
![image](https://user-images.githubusercontent.com/6706496/61359362-bff82f80-a8ae-11e9-934b-0f82de1b3b8d.png)

**Comment by virtuecai** [comment]
尴尬+颤抖， 权限管理这块还没有

**Comment by virtuecai** [comment]
> 1.点击审核详情 没有反应
> 2.动态权限问题，不同用户访问不同页面
> 目前普通用户访问总是提示这个
> ![image](https://user-images.githubusercontent.com/6706496/61359362-bff82f80-a8ae-11e9-934b-0f82de1b3b8d.png)

因为只有 admin 授权了，权限这块功能还没有，ums_admin_role_relation
