### ISSUE TITLE
mall-app 可以开源吗？ 

### ISSUE THREAD

**Issue by 693614965** [macrozheng/mall-admin-web#44]
现在只有后台服务和前端管理UI ，没有app ，怎么下单啊。

**Comment by sylc12** [comment]
同求

**Comment by phoeson** [comment]
支持小程序吗

**Comment by KupoGu** [comment]
直接找个开源的，适配接口不就完了吗，真的是伸手党啊

**Comment by jamesxie** [comment]
同求响应式Html5前端

**Comment by jamesxie** [comment]
> 直接找个开源的，适配接口不就完了吗，真的是伸手党啊

有没有合适的开源推荐？支持手机响应式的。

**Comment by Geek-James** [comment]
可以用这个项目配置下接口https://github.com/Geek-James/ddBuy

**Comment by caojiele** [comment]
> 支持小程序吗

支持，可以参考小程序：三诺健康  其中的积分商城后台就是用的mall
