### ISSUE TITLE
老铁 这个axios跨域问题怎么解决

### ISSUE THREAD

**Issue by ghost** [macrozheng/mall-admin-web#46]

**Comment by macrozheng** [comment]
后端解决，可以看下这个[前后端分离项目，如何解决跨域问题](https://mp.weixin.qq.com/s/5UT-7POsvVPyaBSoLMfdwA)

**Comment by Peggy1992** [comment]
我也遇到同样问题   后端代码下载到本地也运行不起来   这没法解决啊

**Comment by Peggy1992** [comment]
跨域问题解决了 =》访问在线接口无需搭建后台环境，只需将config/dev.env.js文件中的BASE_API改为http://39.98.190.128:8080即可;

但账号密码是多少啊

**Comment by Peggy1992** [comment]
账号密码也有了   关注公众号  回复‘体验’即可
