### ISSUE TITLE
mall-admin-web中utils/support.js作用？

### ISSUE THREAD

**Issue by qigecanghai** [macrozheng/mall-admin-web#47]
用谷歌浏览器在登录页面点击登录没反应，在login页面中禁止以下代码才可以：
            // let isSupport = getSupport();
            // if(isSupport===undefined||isSupport==null){
            //   console.log(4)
            //   this.dialogVisible =true;
            //   return;
            // }
它是需要跳转到https://coding.net/?utm_source=macrozheng&utm_medium=banner&utm_campaign=march2019                      拿到一个cookie，这是广告链接？

**Comment by ghost** [comment]
你这都没看懂。。。。 那不就是一个Cookies呀

**Comment by qigecanghai** [comment]
我说了它要拿到一个cookie，你自己看清楚我问的再回答行不？

**Comment by macrozheng** [comment]
只是个弹框提示而已，可以去掉
