### ISSUE TITLE
只要涉及到修改，删除，编辑，就会一直报500错误？是哪里出问题了呢？有人给解答吗？

### ISSUE THREAD

**Issue by innggg** [macrozheng/mall-admin-web#54]

**Comment by innggg** [comment]
比较急？？？大佬们快出现啊

**Comment by xiaolongsoft** [comment]
会不会是数据问题，查查数据库

**Comment by innggg** [comment]
> 会不会是数据问题，查查数据库

我这边没有数据库

**Comment by innggg** [comment]
> 会不会是数据问题，查查数据库

我下载的楼主的源码，运行，数据什么的都有，就是不能改，不能添加修改，删除

**Comment by innggg** [comment]
> 会不会是数据问题，查查数据库

你们的能正常运行吗？

**Comment by innggg** [comment]
> 会不会是数据问题，查查数据库

我查看了一下错误，说是
{"timestamp":"2019-11-04T01:43:03.679+0000","status":500,"error":"Internal Server Error","message":"\n### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: UPDATE command denied to user 'reader'@'172.17.0.5' for table 'oms_order_setting'\n### The error may involve com.macro.mall.mapper.OmsOrderSettingMapper.updateByPrimaryKey-Inline\n### The error occurred while setting parameters\n### SQL: update oms_order_setting     set flash_order_overtime = ?,       normal_order_overtime = ?,       confirm_overtime = ?,       finish_overtime = ?,       comment_overtime = ?     where id = ?\n### Cause: java.sql.SQLSyntaxErrorException: UPDATE command denied to user 'reader'@'172.17.0.5' for table 'oms_order_setting'\n; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: UPDATE command denied to user 'reader'@'172.17.0.5' for table 'oms_order_setting'","path":"/orderSetting/update/1"}

**Comment by innggg** [comment]
几乎每一个都是这个

**Comment by xiaolongsoft** [comment]
ommand denied to user 'reader'@'172.17.0.5' for table 'oms_order_setting' 
没数据库，怎么玩。你肯定不能随便连接别人的数据库啊。有初始化sql文件的。连自己的库吧。

**Comment by innggg** [comment]
> ommand denied to user 'reader'@'172.17.0.5' for table 'oms_order_setting'
> 没数据库，怎么玩。你肯定不能随便连接别人的数据库啊。有初始化sql文件的。连自己的库吧。

你的意思是我自己建个数据库连我自己的？

**Comment by innggg** [comment]
> > ommand denied to user 'reader'@'172.17.0.5' for table 'oms_order_setting'
> > 没数据库，怎么玩。你肯定不能随便连接别人的数据库啊。有初始化sql文件的。连自己的库吧。
> 
> 你的意思是我自己建个数据库连我自己的？

好的好的，太谢谢了，我试试啊，大神，你经常在线吧，万一我又错了，我还在这里问你啊，麻烦了

**Comment by innggg** [comment]
> ommand denied to user 'reader'@'172.17.0.5' for table 'oms_order_setting'
> 没数据库，怎么玩。你肯定不能随便连接别人的数据库啊。有初始化sql文件的。连自己的库吧。

我要是连自己的数据库，那这些接口是不是不能用了

**Comment by innggg** [comment]
> ommand denied to user 'reader'@'172.17.0.5' for table 'oms_order_setting'
> 没数据库，怎么玩。你肯定不能随便连接别人的数据库啊。有初始化sql文件的。连自己的库吧。

那我是不是得自己写接口获取数据？
