### ISSUE TITLE
访问后台地址改为线上地址http://39.98.190.128:8080后，访问的时候为什么访问本地前台还是走的http://localhost:8080/admin/login这个路径啊

### ISSUE THREAD

**Issue by xianyuci** [macrozheng/mall-admin-web#55]

**Comment by xianyuci** [comment]
除了dev.env.js文件中的BASE_API这里要改成线上地址后，还有其他地方要改吗？为什么这里把http://localhost:8080改为http://39.98.190.128:8080访问前台的时候访问路径走的还是http://localhost:8080/admin/login呢。。。奇怪

**Comment by duhj2** [comment]
必须存盘，或者重启一下npm
