### ISSUE TITLE
无法登陆用默认的admin/123456,config/dev.env.js文件中的BASE_API改为http://120.27.63.9:8080即可

### ISSUE THREAD

**Issue by duhj2** [macrozheng/mall-admin-web#57]
无法登陆用默认的admin/123456,config/dev.env.js文件中的BASE_API改为http://120.27.63.9:8080即可

**Comment by yk-ddm** [comment]
？？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"duhj2"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月3日(星期二) 下午2:46
收件人:&nbsp;"macrozheng/mall-admin-web"<mall-admin-web@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[macrozheng/mall-admin-web] 无法登陆用默认的admin/123456,config/dev.env.js文件中的BASE_API改为http://120.27.63.9:8080即可 (#57)




无法登陆用默认的admin/123456,config/dev.env.js文件中的BASE_API改为http://120.27.63.9:8080即可
