### ISSUE TITLE
npm install的时候报错

### ISSUE THREAD

**Issue by zjh726** [macrozheng/mall-admin-web#58]
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (E:\mall-admin-web-master\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (E:\mall-admin-web-master\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at E:\mall-admin-web-master\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\mall-admin-web-master\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\mall-admin-web-master\node_modules\node-sass
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN echarts-liquidfill@2.0.3 requires a peer of echarts@^4.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN v-charts@1.19.0 requires a peer of echarts@>3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-12-05T06_07_43_253Z-debug.log

**Comment by zzh1650998665** [comment]
兄弟你也炸了啊

**Comment by xiohuchi** [comment]
是不是node版本不对？

**Comment by xiohuchi** [comment]
我的没炸，可以运行

**Comment by MysticBao** [comment]
Can't find Python executable "python", you can set the PYTHON env variable.
python的环境变量没有配。

**Comment by LouisTuo** [comment]
npm install的问题的确存在，本人参考解决，[npm install 缺少python环境](https://blog.csdn.net/qq_42886417/article/details/103123659)

**Comment by zzh1650998665** [comment]
thank you！！！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LouisTuo"<notifications@github.com&gt;; 
发送时间: 2019年12月28日(星期六) 晚上6:45
收件人: "macrozheng/mall-admin-web"<mall-admin-web@noreply.github.com&gt;; 
抄送: "zzh"<1650998665@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [macrozheng/mall-admin-web] npm install的时候报错 (#58)




npm install的问题的确存在，本人参考解决，npm install 缺少python环境

**Comment by macrozheng** [comment]
node-sass无法下载会导致构建失败，需要单独设置node-sass的下载源，npm install之前输入以下命令即可：

```bash
# 设置为淘宝的镜像源
npm config set registry https://registry.npm.taobao.org
# linux
SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/ npm install node-sass
# window
set SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass&& npm install node-sass
```
