### ISSUE TITLE
在npm install的时候，出现了错误，对vue的理解不深，希望有大佬能教教 QQ：1650998665

### ISSUE THREAD

**Issue by zzh1650998665** [macrozheng/mall-admin-web#59]
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "E:\python\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (E:\IdeaProject\mall-admin-web\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (E:\IdeaProject\mall-admin-web\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at E:\IdeaProject\mall-admin-web\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "E:\\VUE\\Node\\node.exe" "E:\\IdeaProject\\mall-admin-web\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--li
bsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\IdeaProject\mall-admin-web\node_modules\node-sass
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     E:\node-v10.16.2-win-x64\node_cache\_logs\2019-12-06T09_34_11_279Z-debug.log

**Comment by xiohuchi** [comment]
是不是node版本不对？

**Comment by duhuazhu** [comment]
npm install node-sass

**Comment by macrozheng** [comment]
解决方法参考这个：https://github.com/macrozheng/mall-admin-web/issues/58
