### ISSUE TITLE
请问前端项目部署在虚拟机上，只能在虚拟机上访问到网址，在宿主机上访问不了，是什么原因呢？

### ISSUE THREAD

**Issue by zmzw** [macrozheng/mall-admin-web#60]
请问前端项目部署在虚拟机上，只能在虚拟机上访问到网址，在宿主机上访问不了，是什么原因呢？

**Comment by zmzw** [comment]
打开端口，关闭防火墙都试过的

**Comment by tolower** [comment]
虚拟机上是用什么方式运行的？是npm run dev开发模式还是build之后跑在web服务器里的？如果是前者的话，我遇到过因为绑定了localhost导致的，不知道你是不是这种情况

**Comment by tjlizz** [comment]
宿主上部署的网页在虚拟机中可以访问吗？
