### ISSUE TITLE
登陆页面问题

### ISSUE THREAD

**Issue by liuruyantest** [macrozheng/mall-admin-web#62]
为什么第一次访问登陆页面，登陆进去之后再访问登陆页面就访问不到了

**Comment by 345509960** [comment]
我想问下登录密码是啥？我把.env.development里面的VUE_APP_BASE_API修改为'http://120.27.63.9:8080'，一直提示跨域问题

**Comment by guyaochu** [comment]
我也有同样的问题，当输入localhost8090时，出现登录界面，账号admin密码macro123然而没有效果
