### ISSUE TITLE
开发下不能打开debugger模式

### ISSUE THREAD

**Issue by minggxu9** [macrozheng/mall-admin-web#7]
我看到你使用了
 devtool: '#cheap-module-eval-source-map',

但我本地不启作用。不知道什么原因。

**Comment by IEB-Richard** [comment]
Cheap不可以，改成#eval-source-map，就可以了，我的已经可以调试。
可以参考link
https://vuejs.org/v2/cookbook/debugging-in-vscode.html
以及link（如果你使用webstorm的话）:
https://blog.jetbrains.com/webstorm/2018/01/working-with-vue-js-in-webstorm/

另外注意，Debug只有在你点击Debug按钮自动弹出的浏览器里操作，系统才会在你IDE里设置的断点处停下来。
