### ISSUE TITLE
修改router/index.js 的meta.title 不成功的问题

### ISSUE THREAD

**Issue by lunaQi** [macrozheng/mall-admin-web#70]
export const asyncRouterMap = [
  {
    path: '/pms',
    component: Layout,
    redirect: '/pms/product',
    name: 'pms',
    meta: {title: '修改', icon: 'product'},
    children: [{
      path: 'product',
      name: 'product',
      component: () => import('@/views/pms/product/index'),
      meta: {title: '修改', icon: 'product-list'}
    },

我修改了src/router/index.js中的meta.title，但是在浏览器中显示的依然是未修改的title名，请问这是为什么呢？还需要修改什么地方呢？

**Comment by Koado** [comment]
遇到了同样的问题，请问楼主解决了吗？

**Comment by macrozheng** [comment]
后台设置的titile会替换到src/router/index.js中的，需要在后台设置下。
