### ISSUE TITLE
前端页面看不了

### ISSUE THREAD

**Issue by IThawk** [macrozheng/mall-admin-web#79]
启动前端页面之后：
 @ multi (webpack)-dev-server/client?http://localhost:8090 webpack/hot/dev-server ./src/main.js

然后打开：
http://localhost:8090

出现:
Cannot GET /

**Comment by xiaozhuge007** [comment]
后来服务没启动呀，或者你按照作者说的修改dev.env.js文件中的BASE_API为http://120.27.63.9:8080

**Comment by IThawk** [comment]
修改了，还是不行。请问请求的页面是什么呢？

**Comment by heavy-james** [comment]
我也遇到这个问题，请问解决了吗？

> 修改了，还是不行。请问请求的页面是什么呢？

我也遇到这个问题，请问解决了吗？
