### ISSUE TITLE
在windows系统下npm install 遇到两个问题:1.安全漏洞 25 vulnerabilities (7 low, 13 moderate, 3 high, 2 critical) 2.fsevents@1.2.3不支持windows系统.

### ISSUE THREAD

**Issue by code2038** [macrozheng/mall-admin-web#8]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os"
:"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})

added 1293 packages from 731 contributors and audited 11496 packages in 1065.74s
found 25 vulnerabilities (7 low, 13 moderate, 3 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for detail

**Comment by IEB-Richard** [comment]
我没有遇到你说的这个问题，请问你系统是什么版本的？Win7还是Win10？
