### ISSUE TITLE
sql文件admin不包含权限数据

### ISSUE THREAD

**Issue by thislin12** [macrozheng/mall-admin-web#86]
导致前端对象报错,打开不了前端

**Comment by sqskg** [comment]
大概点了一下【权限】的菜单，没发现报错；能把报错贴出来么

**Comment by macrozheng** [comment]
下载[mall项目](https://github.com/macrozheng/mall)最新版本SQL，再重新导入

**Comment by keweiLv** [comment]
解决了吗，我也是首页登陆报错，提示无权限，已更新到最新SQL
