### ISSUE TITLE
登录跳转问题

### ISSUE THREAD

**Issue by yhhwpp** [macrozheng/mall-admin-web#88]
登录之后，报错 `Error: Redirected when going from "/login" to "/home" via a navigation guard.`

![image](https://user-images.githubusercontent.com/7929656/87895606-7a011900-ca78-11ea-8c03-f55289e04d9e.png)

**Comment by waWayu666** [comment]
同样的问题

**Comment by luoxing200809** [comment]
一样的问题

**Comment by LoEnzo** [comment]
同样的问题，有解决的吗？
![image](https://user-images.githubusercontent.com/43113063/176140838-0657e54a-0146-41be-bead-26fc01f0dbbe.png)

**Comment by LoEnzo** [comment]
router/index.js 加上下面这个控制台提示没有了，弹窗提示还是有，token获取感觉有问题

> const routerPush = Router.prototype.push
Router.prototype.push = function push(location) {
  return routerPush.call(this, location).catch(error=> error)
}
