### ISSUE TITLE
vue调用后台问题请求

### ISSUE THREAD

**Issue by h00279611** [macrozheng/mall-admin-web#9]
请教一个问题：我在linux上部署了VUE前端的项目，同时也在这个机器上部署了相对应的后台服务，但奇怪的是前台的连接不调用这个后台的服务，而是调用我本地windows上起的后台服务，这个是为什么呢？

**Comment by IEB-Richard** [comment]
你检查过你的服务器端口是否已经打开过了吗？端口必须从外部可以访问才可以。
