### ISSUE TITLE
页面添加子路由未能识别

### ISSUE THREAD

**Issue by deux-ex** [macrozheng/mall-admin-web#91]
页面添加子路由未能识别，我已经在 菜单列表和资源列表 添加 路径/test/**    侧边栏上面为什么没有显示。

**Comment by deux-ex** [comment]
页面在 浏览器上面 显示的都是 404

**Comment by sayz2020** [comment]
你是？
如果你是问问题
那这个不是我的项目，你问错人了






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "macrozheng/mall-admin-web"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月20日(星期四) 下午5:51
收件人:&nbsp;"macrozheng/mall-admin-web"<mall-admin-web@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[macrozheng/mall-admin-web] 页面添加子路由未能识别 (#91)





 
页面添加子路由未能识别，我已经在 菜单列表和资源列表 添加 路径/test/**    侧边栏上面为什么没有显示。

**Comment by macrozheng** [comment]
还需把菜单分配给角色，然后角色分配用户才可以显示，具体参考[《大家心心念念的权限管理功能，这次安排上了！》](http://www.macrozheng.com/#/database/mall_permission)
