### ISSUE TITLE
登录成功后自动跳转/admin/info报错

### ISSUE THREAD

**Issue by MrEastWood** [macrozheng/mall-admin-web#98]
请求：
Request URL: http://localhost:8080/admin/info
Request Method: GET
Status Code: 200 
Remote Address: [::1]:8080
Referrer Policy: no-referrer-when-downgrade
返回:
`{"code":401,"message":"暂未登录或token已经过期","data":null}`

看代码是获取http请求头的用户信息没获取到，报错：
`public UmsAdmin getCurrentAdmin() {
        String userStr = request.getHeader(AuthConstant.USER_TOKEN_HEADER);
        **if(StrUtil.isEmpty(userStr)){
            Asserts.fail(ResultCode.UNAUTHORIZED);
        }**
        UserDto userDto = JSONUtil.toBean(userStr, UserDto.class);
        UmsAdmin admin = adminCacheService.getAdmin(userDto.getId());
        if(admin!=null){
            return admin;
        }else{
            admin = adminMapper.selectByPrimaryKey(userDto.getId());
            adminCacheService.setAdmin(admin);
            return admin;
        }
    }`

请求头里的user是什么时候放进去的？看了登录的代码，没有操作请求头啊。

**Comment by macrozheng** [comment]
这个是`mall-swarm`里面的代码吧，请求头里的user是在网关中解析JWT令牌后放入进去的，在`AuthGlobalFilter.filter()`方法中，具体实现可以参考[《微服务权限终极解决方案，Spring Cloud Gateway + Oauth2 实现统一认证和鉴权！》](http://www.macrozheng.com/#/cloud/gateway_oauth2)。
