### ISSUE TITLE
vue element-ui 表单验证 第一次表单验证的结果，在第二次表单验证时仍然存在

### ISSUE THREAD

**Issue by hdtopku** [macrozheng/mall-admin-web#99]
![image](https://user-images.githubusercontent.com/14859466/95016414-6a5f9c80-0685-11eb-9f61-1bef52ab2e03.png)

![image](https://user-images.githubusercontent.com/14859466/95016257-726b0c80-0684-11eb-8d69-9564ea31b45d.png)

我的做法是：
```
watch: {
    dialogVisible() {
      if (!this.dialogVisible && this.$refs.productAttrCateForm) {
        this.$refs.productAttrCateForm.clearValidate()
      }
    }
  }
```

> 参考
[vue element-ui 表单验证 第一次表单验证的结果，在第二次表单验证时仍然存在](https://cloud.tencent.com/developer/article/1628953)

**Comment by macrozheng** [comment]
已修复
